"""uploads project assets wizard fields

Revision ID: 0006
Revises: 0005
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_owner_id'), 'uploaded_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_project_id'), 'uploaded_files', ['project_id'], unique=False)
    op.create_table('project_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_assets_project_id'), 'project_assets', ['project_id'], unique=False)
    # batch mode so the foreign keys also work on SQLite (it is a no-op wrapper on PostgreSQL)
    with op.batch_alter_table('deliverables') as batch:
        batch.add_column(sa.Column('file_id', sa.String(length=36), nullable=True))
        batch.create_foreign_key('fk_deliverables_file_id', 'uploaded_files', ['file_id'], ['id'])
    with op.batch_alter_table('messages') as batch:
        batch.add_column(sa.Column('attachment_file_id', sa.String(length=36), nullable=True))
        batch.create_foreign_key('fk_messages_attachment_file_id', 'uploaded_files', ['attachment_file_id'], ['id'])
    op.add_column('projects', sa.Column('video_duration', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('style', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('deliverables', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('revisions', sa.Integer(), server_default=sa.text('2'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'revisions')
    op.drop_column('projects', 'deliverables')
    op.drop_column('projects', 'style')
    op.drop_column('projects', 'video_duration')
    with op.batch_alter_table('messages') as batch:
        batch.drop_constraint('fk_messages_attachment_file_id', type_='foreignkey')
        batch.drop_column('attachment_file_id')
    with op.batch_alter_table('deliverables') as batch:
        batch.drop_constraint('fk_deliverables_file_id', type_='foreignkey')
        batch.drop_column('file_id')
    op.drop_index(op.f('ix_project_assets_project_id'), table_name='project_assets')
    op.drop_table('project_assets')
    op.drop_index(op.f('ix_uploaded_files_project_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_owner_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
